version: '3'
services:

  db-car-inventory:
    container_name: db-car-inventory
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: car_inventory_db
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-booking_db:
    container_name: db-booking_db
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test123
    ports:
      - 5435:5432
   


  db-payments:
    container_name: db-payments
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test123
    ports:
      - 5433:5432
   
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
  
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test123
    ports:
      - 5436:5432
   
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev", "--import-realm"]
    ports:
      - 8181:8181
    expose:
      - 8181
    depends_on:
      - db-keycloak
    volumes:
      - ./data/keycloak-realm:/opt/keycloak/data/import
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5436
      DB_USER: Test
      DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181
  
  ### RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    